Update to bevy 0.15
Plonq/bevy_panorbit_camera pull request #87
Opened 2024-11-12 21:33 UTC by dmlukichev

Updated library code, examples and documentation to work with bevy 0.15-rc.3

2024-11-13 08:26 UTC, Plonq commented
Hey, thanks for this, looks like significant changes which saves me time 😄 

I won't merge until Bevy 15 is fully released, but this is a good head start.

2024-11-13 08:27 UTC, Plonq requested changes
Please fix the failed checks

2024-11-13 08:27 UTC, Plonq commented on .gitignore
> +.idea
This should go in your [global gitignore file](https://sebastiandedeyne.com/setting-up-a-global-gitignore-file/)

2024-11-13 12:38 UTC, dmlukichev commented
Formatting fixed, gitignore changes reverted.
I was hoping that you will publish rc version also, but it's up to you to decide.
Thank you for your lib!

2024-11-14 06:07 UTC, Plonq commented
> I was hoping that you will publish rc version also, but it's up to you to decide.

I hadn't thought of that, but the egui feature is broken until `bevy_egui` is updated, so I don't think it's appropriate to release it as RC. Unless `bevy_egui` puts out an RC version It'll have to wait.

2024-11-30 00:36 UTC, Plonq commented
Waiting for https://github.com/vladbat00/bevy_egui/pull/309

2024-11-30 16:30 UTC, pta2002 commented
@Plonq that PR is merged and `bevy_egui` 0.31 is now released with official support for bevy 0.15. Does that mean that this is ready to get merged?

2024-12-01 05:19 UTC, Plonq commented
@dmlukichev Can you do the following please:

* Update deps (bevy to 0.15 and bevy_egui)
* Revert the version and changelog updates (I prefer to do them separately)

2024-12-02 16:25 UTC, dmlukichev commented
Hi, @Plonq. Done.

2024-12-03 07:24 UTC, Plonq commented
For some reason I am unable to push changes to this PR. You need to add `bevy_window` feature to the prod bevy dependency to fix the build.

2024-12-03 22:12 UTC, mineichen commented
Instead of adding Camera3d() to every location, PanOrbitCamera is added, you could add Camera3D as a "required component" and remove `Camera3d::default()` from the examples.

In Plugin::build
```rust
app.register_required_components::<PanOrbitCamera, Camera3d>()
```

2024-12-04 23:36 UTC, dmlukichev commented
Guys, sorry. Not in a position to argue.
It looks like like @mineichen tracks bevy's changes better that I do. I hope he will update this MR accordingly.
Best of luck, Dima

2024-12-05 07:15 UTC, Plonq commented
@dmlukichev Don't worry about that, let's just get this PR fixed and merged.

@mineichen It's a good idea, feel free to open a new PR, or I will later

2024-12-07 03:39 UTC, Plonq commented
I made the necessary changes in https://github.com/Plonq/bevy_panorbit_camera/pull/90, so I'll close this one.

2024-12-07 03:39 UTC, closed without merging